GET /plugins/ returns both installed and available plugins
cheshire-cat-ai/core pull request #387
Opened 2023-08-01 11:52 UTC by valentimarco

# Description

2 new function to retrieve from registry all external plugins available and to install plugins by url.

For now the implementation of "retrieve from registry" bricks plugin page on admin!

Related to issue #300 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2023-08-04 15:55 UTC, pieroit requested changes

2023-08-04 15:55 UTC, pieroit commented on core/cat/routes/plugins.py
> +@router.post("/upload/wa")
Endpoint is `/upload/registry`

2023-08-04 15:55 UTC, pieroit commented on core/cat/routes/plugins.py
> +async def download_plugin_from_registry(request: Request,background_tasks: BackgroundTasks,url_repo: Dict = Body(example={"url": "https://example.com/file.zip"})):
Example should be the URL of a plugin on github

2023-08-04 15:55 UTC, pieroit commented on core/cat/routes/plugins.py
> +        response.raise_for_status()
Use `HTTPException` from fastAPI (consistent across al endpoints)

2023-08-04 16:27 UTC, pieroit commented
Why closed? Just put the PR as a draft until you finish :)

2023-08-04 17:59 UTC, valentimarco commented
i didn't nothing, i synced the fork. Maybe that?

2023-08-04 18:11 UTC, pieroit commented
I see zero commits on the PR
Let me know, you can reopen this or maie a new one

2023-08-04 18:22 UTC, valentimarco commented
> I see zero commits on the PR Let me know, you can reopen this or create a new one

Re open the PR

2023-08-08 08:25 UTC, merged

2023-08-08 08:28 UTC, pieroit commented
Thanks @valentimarco congrats on your merged PR :D

Let's wait a little before testing this code because the responsibility of finding and caching the .zip file of plugins may rest on [this repo](https://github.com/cheshire-cat-ai/awesome-plugins-backend).

Let's discuss this further with @EugenioPetulla @nicola-corbellini