Plugin object not active by default
cheshire-cat-ai/core pull request #433
Opened 2023-08-26 17:58 UTC by Pingdred

# Description

A `Plugin` object is now create not active by default, the manifest is loaded but no modules are imported.
Aligned also tests and the `MadHatter`.

A newly installed plugin is still activated by default, this PR does not change the behavior of the `MadHatter`.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

2023-08-26 18:05 UTC, Pingdred commented on core/cat/mad_hatter/plugin.py
>          self._active = False
@pieroit  I leaved the active attribute, although at the moment it is not used i think it is useful to quickly check if a plugin have loaded hook and tools

2023-08-28 15:39 UTC, pieroit requested changes

2023-08-30 14:33 UTC, Pingdred commented on core/tests/mad_hatter/test_plugin.py
> -def test_create_active_plugin(plugin):
My bad, i thought this checks are in `test_activate_plugin`

2023-08-30 14:46 UTC, Pingdred commented
I put the tests on hooks and tools that were previously in `test_create_active_plugin` into `test_activate_plugin`, plus some little edit to use the plugin fixture. Let me know what you think.

2023-09-01 12:03 UTC, merged