Added Link attribute in Embedder and LLM python files
cheshire-cat-ai/core pull request #536
Opened 2023-10-31 14:04 UTC by mustafaazad03

# Description

In this PR, Issue addressed #530 where I added specific links in embedder and LLM file to point the specific embedder.

Related to issue #530 

## Type of change

- [x] Added specific links in the embedder file
- [x] Added specific link attribute in LLM file

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2023-10-31 14:05 UTC, zAlweNy26 commented
Please don't change the dockerfile.

2023-10-31 14:07 UTC, nicola-corbellini requested changes

2023-10-31 14:07 UTC, nicola-corbellini commented on core/Dockerfile
> +RUN curl -sL https://github.com/cheshire-cat-ai/admin-vue/releases/download/Admin/release.zip | jar -xv
Please, this should not be changed

2023-10-31 14:10 UTC, Pingdred commented
You have created the branch for the PR from main, please close and reopen it by making the PR from develop to develop, thanks.

2023-11-01 02:38 UTC, mustafaazad03 commented on core/Dockerfile
> +RUN curl -sL https://github.com/cheshire-cat-ai/admin-vue/releases/download/Admin/release.zip | jar -xv
sorry for this, I change the file.

2023-11-01 09:41 UTC, nicola-corbellini reviewed
The code is good now, but still you are bringing the commits from the `main` branch. As @Pingdred suggested, you should close this PR, create a new branch starting from `develop`, do your changes and open a new PR. Thank you

2023-11-03 11:33 UTC, pieroit commented
@mustafaazad03 plese redo the PR from `develop` branch, otherwise we close this

2023-11-03 11:34 UTC, closed without merging

2023-11-03 11:35 UTC, mustafaazad03 commented
Ok sure