Added the environment variables Improve Dockerfile with env variables #800
cheshire-cat-ai/core pull request #805
Opened 2024-05-06 04:19 UTC by manjarisri

# Description

I have added the environment variables in the Dockerfile
Related to issue #800 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [.] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-05-07 10:38 UTC, pieroit commented
Thanks @manjarisri !
Reviewing and merging soon ;)

2024-05-07 17:20 UTC, pieroit requested changes

2024-05-07 17:20 UTC, pieroit commented on core/Dockerfile
> +ENV PYTHONUNBUFFERED=1
Please move those two lines up, just afet the `FROM`

2024-05-07 17:20 UTC, pieroit commented on core/Dockerfile
> +ENV PYTHONUNBUFFERED=1
Additional changes:
- please redo the PR branching off `develop` and towards `develop` (`main` is only for release)
- also update `docker-compose.yml` and take away the unnecessary env vars `PYTHONUNBUFFERED` and `WATCHFILES_FORCE_POLLING`

2024-05-08 02:50 UTC, closed without merging

2024-05-08 02:50 UTC, manjarisri commented
sure @pieroit

2024-05-08 03:01 UTC, manjarisri commented
hey @pieroit, i have raised a new PR, please check

thanks