feat: issue #980
cheshire-cat-ai/core pull request #982
Opened 2024-12-03 18:42 UTC by giuseppe-coco

Related to issue #980 

# Checklist:

- [ ] Tests

2024-12-04 11:26 UTC, giuseppe-coco commented
Hi, I fixed the error

2024-12-04 20:00 UTC, matteocacciola requested changes
Take care about https://github.com/cheshire-cat-ai/core/blob/f14f2c0acebddd3f1f1efb6ba3b161bea45e9e3a/core/cat/mad_hatter/mad_hatter.py#L198 and https://github.com/cheshire-cat-ai/core/blob/f14f2c0acebddd3f1f1efb6ba3b161bea45e9e3a/core/cat/mad_hatter/mad_hatter.py#L219

2024-12-04 21:33 UTC, matteocacciola requested changes

2024-12-04 21:33 UTC, matteocacciola commented on core/cat/mad_hatter/plugin.py
> +            return self._plugin_overrides["settings_schema"]()
please, consider that `self._plugin_overrides` becomes a `Dict[str, CatPluginDecorator]`. Therefore, each time you want to run the function related to an item of `self._plugin_overrides`, you should run `self._plugin_overrides[key].function()`

2024-12-04 23:14 UTC, matteocacciola requested changes

2024-12-04 23:14 UTC, matteocacciola commented on core/cat/mad_hatter/mad_hatter.py
> +                        function(self.plugins[plugin_id])
```
if "deactivated" in self.plugins[plugin_id]._plugin_overrides:
    self.plugins[plugin_id]._plugin_overrides["deactivated"].function(self.plugins[plugin_id])

2024-12-04 23:14 UTC, matteocacciola commented on core/cat/mad_hatter/mad_hatter.py
> +                        function(self.plugins[plugin_id])
As above

2024-12-05 10:19 UTC, giuseppe-coco commented
from the _develop_ branch, from which I created the branch for _issue#980_, neither _cat_ nor _pytest_ can be launched, due to the error: `ModuleNotFoundError: No module named ‘langchain_anthropic’`. 
This is why the development of this simple enhancement is becoming time-consuming 😕

2024-12-06 14:30 UTC, pieroit commented
> from the _develop_ branch, from which I created the branch for _issue#980_, neither _cat_ nor _pytest_ can be launched, due to the error: `ModuleNotFoundError: No module named ‘langchain_anthropic’`. This is why the development of this simple enhancement is becoming time-consuming 😕

why is Anthropic needed here?
BTW should be supported natively in `develop`

2024-12-08 15:18 UTC, giuseppe-coco commented
hi, is there anything else that needs to be done for this PR?

2024-12-08 15:54 UTC, pieroit commented
> hi, is there anything else that needs to be done for this PR?

No, just wait I'll review soon
Thansk

2025-02-20 16:53 UTC, merged

2025-02-20 16:55 UTC, pieroit commented
Thanks @giuseppe-coco and sorry for taking so much time.
Added some tests for `@plugin` in `tests/mad_hatter/test_plugin.py`